<?php

declare(strict_types=1);

/**
 * Incremental migration — Batch C: the optional profile image (FR-40).
 *
 * NON-DESTRUCTIVE, for the same reason Batch A is: scripts/migrate.php drops
 * and recreates all 13 tables, and this installation holds real demo data the
 * client will screenshot. This script only ALTERs, so every user, submission,
 * uploaded file and review survives it.
 *
 * Usage:  php scripts/migrate_batch_c.php
 *
 * IDEMPOTENT: the one step asks information_schema whether the column is
 * already there and skips itself if so. There is no migrations table — the
 * check IS the record, exactly as in migrate_batch_a.php.
 *
 * Only ONE column is added. What the file is called on disk is generated by
 * the application (u<id>_<random>.<ext>), so the column holds a bare filename,
 * never a path the user supplied and never a directory: the directory is
 * composed server-side in AvatarController, so a stored value can never point
 * outside storage/avatars/. The image's MIME type is deliberately NOT stored —
 * AvatarController::show() re-derives it from the stored bytes with
 * getimagesize(), so the Content-Type it sends can never be anything the
 * uploader chose.
 *
 * Refuses to run outside development, matching migrate.php and
 * migrate_batch_a.php. APP_ENV defaults to production when unset — the safe
 * direction.
 */

require dirname(__DIR__) . '/config/env.php';
$config = require dirname(__DIR__) . '/config/config.php';
$db = $config['db'];

if ($config['app']['env'] !== 'development') {
    fwrite(STDERR, "REFUSED: APP_ENV is '{$config['app']['env']}', not 'development'.\n");
    fwrite(STDERR, "Database: {$db['name']} on {$db['host']}:{$db['port']} as {$db['user']}.\n");
    fwrite(STDERR, "This script alters a live schema; run it deliberately, from a development config.\n");
    exit(1);
}

$stepNo = 0;

function step(string $message): void
{
    global $stepNo;
    $stepNo++;
    echo sprintf("[%d] %s\n", $stepNo, $message);
}

function done(string $message): void
{
    echo "      -> {$message}\n";
}

function skip(string $message): void
{
    echo "      -> SKIP ({$message})\n";
}

function columnExists(PDO $pdo, string $schema, string $table, string $column): bool
{
    $stmt = $pdo->prepare(
        'SELECT 1 FROM information_schema.COLUMNS
         WHERE TABLE_SCHEMA = :schema AND TABLE_NAME = :table AND COLUMN_NAME = :column
         LIMIT 1'
    );
    $stmt->execute([':schema' => $schema, ':table' => $table, ':column' => $column]);

    return $stmt->fetchColumn() !== false;
}

try {
    $dsn = sprintf('mysql:host=%s;port=%s;dbname=%s;charset=%s', $db['host'], $db['port'], $db['name'], $db['charset']);
    $pdo = new PDO($dsn, $db['user'], $db['pass'], [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES   => false,
    ]);
    $schema = (string) $db['name'];

    echo "CCIS-DMS — Batch C incremental migration\n";
    echo "Database: {$schema} on {$db['host']}:{$db['port']}\n";
    echo str_repeat('-', 72) . "\n";

    /* ----------------------------------------------------------------- 1 --
     * users.avatar_path — the stored filename of the account's profile image,
     * NULL when there is none (which is every account until someone uploads
     * one; the image is optional by requirement, so NULL is the normal state
     * and not a missing value to be backfilled).
     *
     * VARCHAR(120) against a generated name of at most ~30 characters
     * (u<id>_<16 hex>.<ext>) — room for a longer scheme later without another
     * migration, and still far short of anything that could hold a path.
     */
    step('ADD COLUMN users.avatar_path (FR-40)');
    if (columnExists($pdo, $schema, 'users', 'avatar_path')) {
        skip('column already exists');
    } else {
        $pdo->exec('ALTER TABLE users ADD COLUMN avatar_path VARCHAR(120) DEFAULT NULL AFTER program_id');
        done('column added');
    }

    /* ----------------------------------------------------------------- 2 --
     * Report what survived, so the operator can see at a glance that this was
     * not a rebuild.
     */
    step('Verify');
    $users = (int) $pdo->query('SELECT COUNT(*) FROM users')->fetchColumn();
    $withAvatar = (int) $pdo->query('SELECT COUNT(*) FROM users WHERE avatar_path IS NOT NULL')->fetchColumn();
    $submissions = (int) $pdo->query('SELECT COUNT(*) FROM submissions')->fetchColumn();
    $documents = (int) $pdo->query('SELECT COUNT(*) FROM document_files')->fetchColumn();
    done(sprintf('%-20s %d row(s)', 'users', $users));
    done(sprintf('%-20s %d row(s)', '  with a photo', $withAvatar));
    done(sprintf('%-20s %d row(s)', 'submissions', $submissions));
    done(sprintf('%-20s %d row(s)', 'document_files', $documents));

    echo str_repeat('-', 72) . "\n";
    echo "DONE. Batch C applied. Re-running this script is safe — every step is idempotent.\n";
} catch (Throwable $e) {
    fwrite(STDERR, "\nBatch C migration FAILED: {$e->getMessage()}\n");
    fwrite(STDERR, "Nothing after the failing step ran. Fix the cause and re-run — completed steps skip themselves.\n");
    exit(1);
}
